In [2]:
import numpy as np

In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

    How many negative numbers are there?

In [5]:
(a < 0).sum()

4

In [6]:
len(a[a < 0])

4

    How many positive numbers are there?

In [7]:
(a > 0).sum()

5

In [8]:
a.shape

(12,)

In [9]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

    How many even positive numbers are there?

In [12]:
# two conditions:
# even numbers: a, where a % 2 == 0
# positive numbers: a, where a > 0
# cond 1: a[a%2==0], condition2: a[a>0]
# link these two things: 
# i need to use the special and: &
len(a[(a > 0) & (a % 2 == 0)])

3

In [14]:
# i can still depend on boolean values rendering
# as 1's and 0's,
# i just need to wrap the whole thing in parenthesis
# to call a sum on the numpy array of bools
((a > 0) & (a % 2 == 0)).sum()

3

    If you were to add 3 to each data point, how many positive numbers would there be?

In [15]:
# adding 3 to a:
a + 3

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [17]:
((a + 3) > 0).sum()

10

    If you squared each number, what would the new mean and standard deviation be?

In [20]:
# getting mean: np.array.mean(), std: np.array.std()
(a ** 2).mean()

74.0

In [21]:
(a ** 2).std()

144.0243035046516

A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [22]:
# mean: a.mean()
a.mean()

3.0

In [23]:
# centered:
a - a.mean()

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

    Calculate the z-score for each data point. Recall that the z-score is given by:
    Z=(x−μ)/σ

In [24]:
# data point - mean of data points / std of data points
(a - a.mean()) / a.std()

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

## Setup 1

In [25]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:

Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [26]:
sum(a)

55

In [27]:
sum_of_a = 0
for i in a:
    sum_of_a += i
    
sum_of_a

55

Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [28]:
min(a)

1

In [29]:
for i, elm in enumerate(a):
    if i == 0:
        min_value = elm
    else:
        if elm < min_value:
            min_value = elm

min_value

1

Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [31]:
for i, elm in enumerate(a):
    if i == 0:
        max_value = elm
    else:
        if elm > max_value:
            max_value = elm

max_value

10

In [32]:
max_value == max(a)

True

Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [36]:
mean_of_a = sum(a) / len(a)

In [37]:
mean_of_a

5.5

Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [39]:
# initialize at 1:
prod_of_a = 1
for i in a:
    # prod_of_a = prod_of_a * i
    prod_of_a *= i
prod_of_a

3628800

Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [40]:
squares_of_a = []
# for loops:
# for element in iterable:
#     do this action
for i in a:
    squares_of_a.append(i**2)
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [41]:
# with a list comprehension:
# do the action on the element for every element in this iterable
[i**2 for i in a]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [43]:
odds_in_a = []
for num in a:
    if num % 2 == 1:
        odds_in_a.append(num)

In [44]:
odds_in_a

[1, 3, 5, 7, 9]

In [46]:
[number for number in a if number % 2 == 1]

[1, 3, 5, 7, 9]

Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [47]:
[number for number in a if number % 2 == 0]

[2, 4, 6, 8, 10]

What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [48]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [49]:
overall_sum = 0
for i in b:
    overall_sum += sum(i)
overall_sum

33

Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

In [50]:
# convert b to a numpy array:
b = np.array(b)

In [51]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [52]:
sum_of_b = b.sum()

In [53]:
sum_of_b

33

Exercise 2 - refactor the following to use numpy. 

min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [54]:
b.min()

3

Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [55]:
max_of_b = b.max()
max_of_b

8

# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [57]:
mean_of_b = b.mean()
mean_of_b

5.5

In [58]:
# to get the docstring inside a notebook:
# start typing the thing
# once you're at the opening paren:
# hit shift+tab
# i.e.: np.array(*shift+tab*

Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

#### easy way: doing it with an array

product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [60]:
product_of_b = np.prod(b)
product_of_b

20160

Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [61]:
# [i**2 for i in b]
#yay vectorization!
squares_of_b = b ** 2
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [62]:
np.sum(b)

33

In [63]:
b.sum()

33

In [65]:
sum(sum(b))

33

Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [68]:
# checking if the elements are odd:
#  % 2 == 1
odds_in_b = b[b % 2 == 1]
odds_in_b

array([3, 5, 7])

Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [69]:
evens_in_b = b[b % 2 == 0] #b, where b mod 2 is 0
evens_in_b

array([4, 6, 8])

Exercise 9 - print out the shape of the array b.

In [70]:
b.shape

(2, 3)

Exercise 10 - transpose the array b.

In [72]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [71]:
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [73]:
b.T

array([[3, 6],
       [4, 7],
       [5, 8]])

Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [76]:
np.reshape(b, (6,))

array([3, 4, 5, 6, 7, 8])

In [77]:
b.tolist()

[[3, 4, 5], [6, 7, 8]]

In [78]:
b.flatten()

array([3, 4, 5, 6, 7, 8])

Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [83]:
# 6 rows of 1 element: (6,1)
np.reshape(b, (6,1)).tolist()

[[3], [4], [5], [6], [7], [8]]

In [84]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [85]:
c

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [86]:
c = np.array(c)

HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
Exercise 1 - Find the min, max, sum, and product of c.

In [88]:
labels = ['max', 'min', 'sum', 'prod']
outputs = c.max(), c.min(), c.sum(), np.prod(c)

In [89]:
outputs

(9, 1, 45, 362880)

In [90]:
labels

['max', 'min', 'sum', 'prod']

In [96]:
c_stats = dict(zip(labels, outputs))

In [97]:
c_stats

{'max': 9, 'min': 1, 'sum': 45, 'prod': 362880}

Exercise 2 - Determine the standard deviation of c.

In [94]:
my_arrays = {
    'a': a,
    'b': b,
    'c': c} 

In [95]:
my_arrays['b']

array([[3, 4, 5],
       [6, 7, 8]])

In [98]:
c_stats['std'] = my_arrays['c'].std()

In [99]:
c_stats

{'max': 9, 'min': 1, 'sum': 45, 'prod': 362880, 'std': 2.581988897471611}

In [100]:
my_arrays['c']

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Exercise 3 - Determine the variance of c.

In [101]:
c_stats['var'] = my_arrays['c'].var()

In [102]:
c_stats['var'], c_stats['std']

(6.666666666666667, 2.581988897471611)

In [103]:
c_stats['std'] ** 2

6.666666666666666

Exercise 4 - Print out the shape of the array c

In [104]:
c_stats

{'max': 9,
 'min': 1,
 'sum': 45,
 'prod': 362880,
 'std': 2.581988897471611,
 'var': 6.666666666666667}

In [106]:
a_stats, b_stats = {}, {}
my_content = {
    'a': {'array':a, 'stats': a_stats},
    'b': {'array': b, 'stats': b_stats},
    'c': {'array': c, 'stats': c_stats}
}

In [107]:
my_content['c']['array']

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
my_content['c']['stats']

{'max': 9,
 'min': 1,
 'sum': 45,
 'prod': 362880,
 'std': 2.581988897471611,
 'var': 6.666666666666667}

Exercise 5 - Transpose c and print out transposed result.

In [109]:
my_content['c']['array'].T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [110]:
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Exercise 6 - Get the dot product of the array c with c. 

In [111]:
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [113]:
(c * c.T).sum()

261

Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [115]:
np.prod(c * c.T)

131681894400

In [117]:
## Setup 4
my_content['d'] = {'array': 
[
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]}

In [118]:
my_content['d']['array']

[[90, 30, 45, 0, 120, 180],
 [45, -90, -30, 270, 90, 0],
 [60, 45, -45, 90, -45, 180]]

In [119]:
# initialize a dictionary to hold the stats
my_content['d']['stats'] = {}

Exercise 1 - Find the sine of all the numbers in d

In [121]:
my_content['d']['stats']['sin'] = np.sin(
    my_content['d']['array'])

In [122]:
my_content['d']['stats']['sin']

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

Exercise 2 - Find the cosine of all the numbers in d

In [123]:
my_content['d']['stats']['cos'] = np.cos(
    my_content['d']['array'])

Exercise 3 - Find the tangent of all the numbers in d

In [124]:
my_content['d']['stats']['tan'] = np.tan(
    my_content['d']['array'])

Exercise 4 - Find all the negative numbers in d

In [127]:
type(d)

list

In [128]:
# lets convert that to an array

In [129]:
d = np.array(d)
d[d < 0]

array([-90, -30, -45, -45])

In [130]:
type(my_content['d']['array'])

list

In [131]:
my_content['d']['array'] = np.array(d)

Exercise 5 - Find all the positive numbers in d

In [134]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [133]:
my_positive_mask

[array([[ True,  True,  True, False,  True,  True],
        [ True, False, False,  True,  True, False],
        [ True,  True, False,  True, False,  True]])]

In [135]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [137]:
d > 0

array([[ True,  True,  True, False,  True,  True],
       [ True, False, False,  True,  True, False],
       [ True,  True, False,  True, False,  True]])

In [140]:
type([d > 0])

list

In [136]:
# my positive mask exists just as the boolean
# assessment which already outputs an array
# if we put brackets in the assignment,
# we create a layer of unintended nesting
# which will not work for when we try to apply the mask,
# which would be like saying to python d[[d > 0]] compared to d[d > 0]
my_positive_mask = d > 0
d[my_positive_mask]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

Exercise 6 - Return an array of only the unique numbers in d.

In [142]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

Exercise 7 - Determine how many unique numbers there are in d.

In [143]:
# the last one output an array,
# lets get the shape of that thing

In [148]:
d.shape

(3, 6)

In [149]:
d.size

18

In [151]:
len(d)

3

In [147]:
np.unique(d).size

11

In [150]:
len(np.unique(d))

11

Exercise 8 - Print out the shape of d.

In [152]:
d.shape

(3, 6)

Exercise 9 - Transpose and then print out the shape of d.

In [153]:
d_transpose = d.T

In [154]:
d_transpose.shape

(6, 3)

In [155]:
d.T.shape

(6, 3)

Exercise 10 - Reshape d into an array of 9 x 2

In [157]:
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])